server:
  port: 8080

# datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.34:3306/test?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

logging:
  level:
    root: warn
    com.thd.dao: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.thdbd.dao